main:
  # IP information for network adapter
  FixServer: 127.0.0.1
  FixPort: 3490
  screenWidth: 1000
  screenHeight: 700

charts_dir: charts

icon_scale: 0.5
icon_fill: mediumorchid
icon_outline: white
icon_opacity: .9
zoom: 1.0
show_path: True
chart_type: Sectional
north_is_up: True
extended_track_length: 200
el_color: black

displays:
    GPS:
        columns: 2
        keys:
            - TRACKM
            - GS
        description_overrides:
            - Mag Track
            - GS
        position: [-20, 20]
        css_styles: "background-color: gray;border-style: solid ;border-width: 2 ;border-color: black; color: darkblue"
        item_css_styles: "border-style: none"

menu:
  menus:
      MainMenu:
        - ['Zoom', 'set menu focus', "ZOOM"]
        - ['Chart Type', 'set menu focus', "Chart Type"]
        - ['Debug', 'logging.getLogger().setLevel(1 if logging.getLogger().getEffectiveLevel() > 1 else logging.INFO)', None]
  start_menu: MainMenu
  number_of_buttons: 3
  buttons_spacing: 120
  left_margin: 100
  top_margin: 5

# The keybindings are used to attach keystrokes to actions.  The key can be
# a string that represents a key Sequence.  See the documentation for more
# information about key sequences and actions.
keybindings:
  - key: F1
    action: Activate Menu Item
    args: 1
  - key: F2
    action: Activate Menu Item
    args: 2
  - key: F3
    action: Activate Menu Item
    args: 3
  - key: F4
    action: Activate Menu Item
    args: 4
  - key: F5
    action: Activate Menu Item
    args: 5
  - key: F6
    action: Activate Menu Item
    args: 6

# Data bindings tie actions to values in the database
# key is the database key and should match the FIX Gateway key
databindings:
  - key: BTN1
    condition: True
    action: Activate Menu Item
    args: 1
  - key: BTN2
    condition: True
    action: Activate Menu Item
    args: 2
  - key: BTN3
    condition: True
    action: Activate Menu Item
    args: 3
  - key: BTN4
    condition: True
    action: Activate Menu Item
    args: 4
  - key: BTN5
    condition: True
    action: Activate Menu Item
    args: 5
  - key: BTN6
    condition: True
    action: Activate Menu Item
    args: 6
